# File: docker-compose.yml

services:
  # ===============================
  # Next.js フロントエンド
  # ===============================
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile.nextjs
    container_name: nextjs_app
    ports:
      - "3000:3000"
    depends_on:
      - python-proxy

    # Next.jsコンテナ内で python-proxyに向けて "DEEPSEEK_PYPROXY_HOST=python-proxy:8000"
    environment:
      - DEEPSEEK_PYPROXY_HOST=python-proxy:8000

  # ===============================
  # Pythonプロキシ (Flask)
  # ===============================
  python-proxy:
    build:
      context: ./python-proxy
      dockerfile: Dockerfile
    container_name: python_proxy_app
    # ホスト 18000 => コンテナ 8000 (衝突回避)
    ports:
      - "18000:8000"

    depends_on:
      - deepseek-java

  # ===============================
  # Java(Spring Boot) [任意モック]
  # ===============================
  deepseek-java:
    build:
      context: ./deepseek-java
      dockerfile: Dockerfile
    container_name: deepseek_java_app
    # ホスト 18088 => コンテナ 8088
    ports:
      - "18088:8088"
