version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-legendary-website
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      # MongoDBなど他の.env値を必要に応じて設定
    # volumes: もしホットリロード開発なら ".:/app" とか
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    # volumes:
    #   - mongo-data:/data/db

# volumes:
#   mongo-data:
