# docker-compose.yml
# version: '3' 等は削除推奨 (最近はversion省略が推奨)

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: myDatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"   # Next.js
      - "3006:3006"   # Express custom server port (ただし get-port が3006以外を取ると外部からアクセス不可)
    depends_on:
      - db
      - redis

volumes:
  postgres-data:
