version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: legendary-website
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      # MONGODB_URI: "mongodb://mongo:27017/myDatabase" など
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: my-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    # volumes:
    #   - mongo-data:/data/db

# volumes:
#   mongo-data:
