# docker-compose.yml
version: "3.9"
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      # build時&実行時に .env を読み込ませる場合
      MONGODB_URI: ${MONGODB_URI}
    # もしdocker-compose起動時に .env の設定を読み込ませたくない場合は別方法
