# docker-compose.yml
services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "mongodb+srv://<username>:<pass>@<cluster>.mongodb.net/db?retryWrites=true&w=majority"
      OPENAI_API_KEY: "sk-XXXX"
      REDIS_URL: "redis://redis:6379"
    depends_on:
      - redis
    #  - db (MongoはAtlas利用なら不要)

  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
