version: "3.9"
services:
  db:
    image: mongo:6
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:7.2-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: x-clone
    ports:
      - "3000:3000"
      - "3006:3006"
    environment:
      MONGODB_URI: "mongodb://root:secret@db:27017/myDatabase?authSource=admin"
    depends_on:
      - db
      - redis

volumes:
  mongo-data:
